import { createContext, useContext, useState, useEffect } from 'react';
import apiCall from '@/lib/api';

const translations = {
  en: {
    // Navigation & General
    appName: 'SwasthyaSetu',
    appSubtitle: 'National Emergency & Healthcare Resource Network',
    emergencyHealthcareNetwork: 'Emergency Healthcare Network',
    navHome: 'Home',
    navHospitals: 'Hospitals & Beds',
    navHospitalsShort: 'Hospitals',
    navBlood: 'Blood Availability',
    navBloodShort: 'Blood',
    navDonors: 'Blood Donors',
    navEmergency: 'Emergency SOS',
    navProfile: 'Profile',
    emergencyHelp: 'Emergency Help',
    adminLogin: 'Admin Login',
    registerHospital: 'Register Hospital',
    switchLanguage: 'हिंदी (HI)',
    platformStatusText: 'verified hospitals and',
    platformStatusTextBlood: 'blood banks are live on SwasthyaSetu. Are you a hospital or blood bank?',
    joinNetworkCTA: 'Join Network',
    noHospitalsTitle: 'No Verified Hospitals Yet',
    noHospitalsDesc: 'No verified hospitals are currently registered in this area. Be the first to register your facility!',
    noBloodTitle: 'No Verified Blood Banks Yet',
    noBloodDesc: 'No verified blood banks are currently registered in this area. Be the first to register your blood bank!',
    registerFacilityCTA: 'Register Facility',
    registerBloodBank: 'Register Blood Bank',

    // Home Page
    heroTitle: 'Real-Time Bed & Blood Emergency Network',
    heroTitleMain: 'Find Emergency Hospital Beds in Real-Time',
    heroTitlePart1: 'Find Emergency',
    heroTitlePart2: 'Hospital Beds in',
    heroTitlePart3: 'Real-Time',
    heroSubtitleMain: 'SwasthyaSetu connects patients to verified hospital beds, ICU units, and live blood availability across India. When every second counts, get real-time verified healthcare support.',
    findEmergencyBed: 'Find Emergency Bed',
    findBed: 'Find Bed',
    findBlood: 'Find Blood',
    requestAmbulance: 'Request Ambulance',
    ambulance: 'Ambulance',
    liveUpdatesIndia: 'Live Updates Across India',
    bedsTracked: 'Beds Tracked',
    heroSubtitle: 'Real-time emergency healthcare network connecting verified hospitals, blood banks, and live ambulance dispatch across India.',
    findNearbyHospitals: 'Find Nearby Hospitals',
    emergencySOSCall: 'Emergency SOS Call (112)',
    liveHospitalNetwork: 'Live Hospital Network',
    verifiedBeds: 'Verified Beds Available',
    bloodUnitsStock: 'Blood Units Available',
    citiesCovered: 'Cities Across India',
    quickEmergencyTitle: 'Need Emergency Medical Help?',
    quickEmergencyDesc: 'Hold an ICU/Ventilator bed for 10 minutes with guaranteed availability while you reach the hospital.',
    reserveBedNow: 'Reserve ICU Bed Now',
    noBedsAvailable: 'No Beds Available',

    // Badges
    verifiedHospitals: 'Verified Hospitals',
    realTimeUpdatesBadge: 'Real-time Updates',
    support24x7Badge: '24x7 Support',

    // Floating Stats
    hospitalsBeds: 'Hospitals & Beds Available',
    bloodBanksAvailable: 'Blood Banks Available',
    activeAmbulances: 'Active Ambulances',
    emergencySupport: 'Emergency Support',

    // Problem Statement
    problemWeSolveTitle: 'The Problem We Solve',
    problemWeSolveDesc: 'During medical emergencies in India, families waste precious time calling hospitals to check bed availability. Many lose loved ones due to delayed care.',
    problemWeSolveShortDesc: 'During medical emergencies in India, families waste precious time calling hospitals.',
    goldenHourLost: 'Golden Hour Lost',
    goldenHourDesc: 'Trauma patients have 60 minutes for life-saving intervention. Most spend this time searching for hospitals.',
    noCentralSystem: 'No Central System',
    noCentralDesc: 'Families call 10-15 hospitals during emergencies. Real-time bed data is not accessible to public.',
    bloodShortage: 'Blood Shortage',
    bloodShortageDesc: 'India faces a shortage of 1.5 million blood units annually. Finding donors during emergencies is chaotic.',

    // How SwasthyaSetu Helps
    howItHelps: 'How SwasthyaSetu Helps',
    howItHelpsDesc: 'A comprehensive platform connecting patients, hospitals, and donors in real-time.',
    smartMatching: 'Smart Matching',
    smartMatchingDesc: 'Intelligent GPS triage finds the nearest verified hospital based on live bed availability.',
    smartMatchingEngine: 'Smart Matching Engine',
    realTimeUpdatesCard: 'Real-Time Updates',
    realTimeUpdatesCardDesc: 'Live bed and blood availability updates from verified hospitals.',
    adminVerified: 'Admin Verified',
    adminVerifiedDesc: 'Hospital infrastructure and bed capacity certified by Super Admin inspection.',
    superAdminVerified: 'Super Admin Verified',
    certifiedWardInventory: 'Certified Ward Inventory',
    routeOptimization: 'Route Optimization',
    routeOptimizationDesc: 'Get the fastest route to your chosen hospital with integrated maps.',
    donorNetwork: 'Donor Network',
    donorNetworkDesc: 'Connect with registered blood donors in your area during emergencies.',
    supportRoundClock: '24x7 Support',
    supportRoundClockDesc: 'Emergency support team available round the clock to assist you.',
    panIndiaCoverage: 'Pan-India Coverage',
    panIndiaCoverageDesc: 'Available across all major cities with expanding hospital network daily.',

    // How It Works
    howItWorks: 'How It Works',
    howItWorksDesc: 'Get connected to the right hospital in three simple steps.',
    shareLocationStep: 'Share Location',
    shareLocationStepDesc: 'Allow location access or enter your address manually.',
    selectEmergencyStep: 'Select Emergency Type',
    selectEmergencyStepDesc: 'Choose emergency type and required bed type (ICU, General, Ventilator).',
    getRecommendationsStep: 'Get Recommendations',
    getRecommendationsStepDesc: 'View top hospitals sorted by distance and availability with routes.',
    everySecondCounts: 'Every Second Counts in an Emergency',
    everySecondCountsDesc: 'Do not waste time calling hospitals. Find available beds instantly with SwasthyaSetu.',
    searchNow: 'Search Now',
    registerAsDonor: 'Register as Donor',

    // Hospitals Page & Cards
    liveBedTracker: 'Live Bed Tracker',
    hospitalsDirectoryTitle: 'Hospital Directory & Bed Occupancy',
    hospitalsDirectoryDesc: 'Real-time hospital capacity, ICU availability, ventilator status, and location guidance.',
    searchHospitalsPlaceholder: 'Search hospitals by city, state, or hospital name...',
    allCities: 'All Cities',
    allBedTypes: 'All Bed Types',
    icuOnly: 'ICU Beds Only',
    ventilatorOnly: 'Ventilator Beds Only',
    generalOnly: 'General Beds Only',
    available: 'Available',
    totalCapacity: 'Total Capacity',
    icuBeds: 'ICU Beds',
    generalBeds: 'General Beds',
    ventilatorBeds: 'Ventilator Beds',
    holdBed: 'Hold Bed (10m)',
    holdingBed: 'Holding Bed...',
    directions: 'Get Directions',
    verified: 'Verified',
    unverified: 'Pending Verification',
    blockchainVerified: 'Verified Facility',
    contactHospital: 'Contact Hospital',
    facilitiesSpecialties: 'Specialties & Facilities',
    noHospitalsFound: 'No hospitals match your selected search or city filters.',
    showingHospitals: 'Showing',
    hospitalsText: 'hospitals',
    verifiedFacilitiesLive: 'Verified facilities live',
    mapView: 'Map View',
    hideMap: 'Hide Map',
    grid: 'Grid',
    list: 'List',
    zoomPinOnMap: 'Zoom Pin on Map 📍',
    phoneNotListed: 'Phone not listed',
    emergency24x7: '24/7 Emergency',
    bedHoldModalTitle: 'Verified Bed Hold (10-Min Limit)',
    bedTicketTitle: 'Bed Reservation Ticket',
    concurrencyLockNotice: 'Concurrency lock & phone OTP verification active.',
    patientName: 'Patient Name',
    enterPatientName: 'Enter patient full name',
    contactPhone: 'Contact Phone Number',
    selectBedCategoryHold: 'Select Bed Category to Hold',
    bedsLeft: 'left',
    selected: 'Selected',
    fullZeroLeft: 'Full / 0 Left',
    noBedsAvailableToHold: 'No Beds Available to Hold',
    selectedBedCategoryFull: 'Selected Bed Category Full',
    proceedPhoneVerification: 'Proceed with Phone Verification',
    generatingLock: 'Generating One-Time Lock...',
    otpSentTo: 'OTP sent to',
    enterOtp: 'Enter 6-Digit OTP',
    back: 'Back',
    verifyOtpHold: 'Verify OTP & Hold Bed',
    verifyingHolding: 'Verifying & Holding...',
    bedHoldActive: 'Bed Hold Active!',
    showQrAtDesk: 'Show QR Pass at Hospital Desk',
    timeRemaining: 'Time Remaining:',
    patientLabel: 'Patient:',
    bedLabel: 'Bed:',
    hospitalLabel: 'Hospital:',
    printTicket: 'Print / Save PDF Ticket (with QR Code)',
    releaseHold: 'Release Hold',
    releasing: 'Releasing...',
    done: 'Done',

    // Blood Page & Cards
    bloodDirectoryTitle: 'National Blood Bank Availability',
    bloodDirectoryDesc: 'Search live blood bank stocks, critical blood types, and verified donors across India.',
    bloodFinder: 'Blood Finder',
    bloodFinderDesc: 'Find blood availability and register as a donor',
    findBloodTab: 'Find Blood',
    donateBloodTab: 'Donate Blood',
    searchBloodAvailability: 'Search Blood Availability',
    findBloodBanksNear: 'Find blood banks with available units near you',
    bloodGroup: 'Blood Group',
    selectBloodGroup: 'Select blood group',
    allBloodGroups: 'All Blood Groups',
    city: 'City',
    selectCity: 'Select city',
    search: 'Search',
    searching: 'Searching...',
    showAll: 'Show All',
    searchBloodStocks: 'Search Blood Stocks',
    allGroups: 'All Blood Groups (A+, B+, O+, AB-...)',
    unitsInStock: 'Units Available',
    units: 'units',
    call: 'Call',
    lastUpdated: 'Last Updated',
    contactBloodBank: 'Contact Blood Bank',
    requestBloodUnits: 'Request Blood Units',
    registerAsBloodDonor: 'Register as Blood Donor',
    joinDonorNetworkDesc: 'Fill in your details to join our donor network',
    fullName: 'Full Name',
    phone: 'Phone',
    email: 'Email',
    ageYears: 'Age (Years)',
    weightKg: 'Weight (kg)',
    registerDonorBtn: 'Register as Donor',
    criticalShortageAlert: 'Critical Shortage: O- & AB- blood units are low in several cities.',
    noBloodFound: 'No blood stocks found for selected city or blood group.',
    foundBloodBanks: 'Found',
    bloodBanksCount: 'blood banks',
    whyDonateBlood: 'Why Donate Blood?',
    saveLives: 'Save Lives',
    saveLivesDesc: 'One donation can save up to 3 lives',
    quickProcess: 'Quick Process',
    quickProcessDesc: 'The entire process takes only 30-45 minutes',
    healthBenefits: 'Health Benefits',
    healthBenefitsDesc: 'Free health checkup and reduced heart disease risk',
    eligibilityCriteria: 'Eligibility Criteria',
    eligibilityAge: 'Age between 18-65 years',
    eligibilityWeight: 'Weight at least 50 kg',
    eligibilityHemoglobin: 'Hemoglobin level above 12.5 g/dL',
    eligibilityIllness: 'No major illness in last 6 months',
    eligibilityGap: '56 days gap from last donation',

    // Emergency Page & Components
    emergencySOSTitle: 'Emergency Medical Dispatch & Bed Hold',
    emergencySOSDesc: 'Instant 10-minute bed reservation with real-time GPS location matching.',
    liveSOSDispatch: 'Live SOS Dispatch',
    emergencySearchTitle: 'Emergency Search',
    emergencySearchDesc: 'Find the nearest hospital with available beds and live ambulance support',
    enterDetails: 'Enter Details',
    selectHospital: 'Select Hospital',
    yourLocation: 'Your Location',
    locationDesc: 'We need your location to find the nearest hospitals with available beds',
    useCurrentLocation: 'Use Current Location',
    detectingLocation: 'Detecting Location...',
    orEnterManually: 'Or enter manually',
    addressLandmark: 'Address / Landmark',
    addressPlaceholder: 'Enter your street, area, or city...',
    gpsDetectedSuccess: 'GPS location detected successfully',
    emergencyDetails: 'Emergency Details',
    emergencyDetailsDesc: 'Help us find the right hospital and equipment for your needs',
    emergencyType: 'Emergency Type',
    selectEmergencyType: 'Select emergency type',
    traumaAccident: 'Trauma/Accident',
    cardiacEmergency: 'Cardiac Emergency',
    strokeEmergency: 'Stroke',
    respiratoryEmergency: 'Respiratory',
    otherEmergency: 'Other',
    requiredBedType: 'Required Bed Type',
    icuBed: 'ICU Bed',
    icuBedDesc: 'Intensive care unit',
    generalBed: 'General Bed',
    generalBedDesc: 'Standard hospital bed',
    ventilator: 'Ventilator',
    ventilatorDesc: 'With ventilator support',
    contactPhoneLabel: 'Contact Phone *',
    patientNameLabel: 'Patient Name (Optional)',
    findHospitalsButton: 'Find Emergency Hospitals',
    findingHospitals: 'Finding Nearest Hospitals...',
    recommendedHospitals: 'Recommended Hospitals',
    modifySearch: 'Modify Search',
    backToSearchForm: 'Back to Search Form',
    callHospital: 'Call Hospital',
    aiMatch: 'AI Match',
    emergencyAmbulanceDispatch: 'Emergency Ambulance Dispatch',
    ambulanceDispatchDesc: 'Real-time GPS tracked emergency ambulances near your location',
    gpsLive: 'GPS LIVE',
    callDriver: 'Call Driver',
    dispatchNow: 'Dispatch Now',
    enRoute: 'En Route',
    noAmbulancesActive: 'No Verified Ambulances Active Yet',
    noAmbulancesDesc: 'No verified ambulances are currently active in this location. Dial emergency line 112 for direct government dispatch.',
    nationalHelplines: 'National Emergency Helplines',
    ambulance102: 'Ambulance Helpline: 102 / 108',
    disaster112: 'National Emergency: 112',
    helplinesTitle: 'Emergency Helplines',
    govtSos: '24/7 Government SOS',
    emergency: {
      helplines: 'Emergency Helplines',
      ambulance: 'Ambulance Helpline',
      national: 'National Emergency'
    },

    // Hospital Onboarding Modal
    hospitalRegisterTitle: 'Hospital Onboarding & Registration',
    hospitalRegisterDesc: 'Connect your hospital to the SwasthyaSetu National Network',
    hospitalFullName: 'Hospital Full Name *',
    hospitalType: 'Hospital Type',
    privateHospital: 'Private Hospital',
    govtHospital: 'Government Hospital',
    charitableHospital: 'Charitable / Trust',
    licenseNumber: 'HFR / Registration License No.',
    phoneContact: 'Emergency Contact Phone',
    cityName: 'City *',
    stateName: 'State / Territory',
    fullAddress: 'Full Address',
    adminLoginEmail: 'Admin Login Email *',
    adminPassword: 'Admin Password *',
    submitApplication: 'Submit Registration Application',
    submittingApp: 'Submitting Application...',
    applicationSubmitted: 'Application Submitted Successfully!',

    // Admin & Login
    hospitalAdminPortal: 'Hospital Admin Portal',
    superAdminControl: 'Super Admin Control Room',
    hospitalStaffLogin: 'Hospital Staff & Nodal Officer Login',
    superAdminLoginTitle: 'Ministry Super Admin Control Room',
    updateBedsButton: 'Update Beds',
    updateBedsTitle: 'Update Bed Availability',
    saveBedUpdates: 'Save Bed Updates',
    cancel: 'Cancel',

    // Footer
    footerDesc: 'SwasthyaSetu is India\'s unified real-time emergency healthcare network powering bed availability, blood stocks, and emergency dispatch.',
    quickLinks: 'Quick Links',
    facilityOnboarding: 'Facility Onboarding',
    registerBloodBankLink: 'Register Blood Bank',
    registerAmbulanceLink: 'Register Ambulance',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    rightsReserved: 'All Rights Reserved. SwasthyaSetu National Health Network.',
    allRightsReservedShort: '© 2026 SwasthyaSetu. All rights reserved.',
    police100: 'Police: 100',
    fire101: 'Fire: 101'
  },
  hi: {
    // Navigation & General
    appName: 'स्वास्थ्य सेतु',
    appSubtitle: 'राष्ट्रीय आपातकालीन एवं स्वास्थ्य संसाधन नेटवर्क',
    emergencyHealthcareNetwork: 'आपातकालीन स्वास्थ्य नेटवर्क',
    navHome: 'होम',
    navHospitals: 'अस्पताल और बेड',
    navHospitalsShort: 'अस्पताल',
    navBlood: 'रक्त उपलब्धता',
    navBloodShort: 'रक्त',
    navDonors: 'रक्तदाता नेटवर्क',
    navEmergency: 'आपातकालीन सेवा (SOS)',
    navProfile: 'प्रोफाइल',
    emergencyHelp: 'आपातकालीन सहायता',
    adminLogin: 'एडमिन लॉगिन',
    registerHospital: 'अस्पताल पंजीकृत करें',
    switchLanguage: 'English (EN)',
    platformStatusText: 'सत्यापित अस्पताल और',
    platformStatusTextBlood: 'ब्लड बैंक स्वास्थ सेतु पर लाइव हैं। क्या आप एक अस्पताल या ब्लड बैंक हैं?',
    joinNetworkCTA: 'नेटवर्क में शामिल हों',
    noHospitalsTitle: 'अभी तक कोई सत्यापित अस्पताल नहीं',
    noHospitalsDesc: 'आपके क्षेत्र में अभी तक कोई सत्यापित अस्पताल पंजीकृत नहीं है। अपनी सुविधा पंजीकृत करने वाले पहले व्यक्ति बनें!',
    noBloodTitle: 'अभी तक कोई सत्यापित ब्लड बैंक नहीं',
    noBloodDesc: 'आपके क्षेत्र में अभी तक कोई सत्यापित ब्लड बैंक पंजीकृत नहीं है। अपना ब्लड बैंक पंजीकृत करने वाले पहले व्यक्ति बनें!',
    registerFacilityCTA: 'सुविधा पंजीकृत करें',
    registerBloodBank: 'ब्लड बैंक पंजीकृत करें',

    // Home Page
    heroTitle: 'रीयल-टाइम बेड एवं ब्लड आपातकालीन नेटवर्क',
    heroTitleMain: 'रीयल-टाइम में आपातकालीन अस्पताल बेड्स खोजें',
    heroTitlePart1: 'आपातकालीन',
    heroTitlePart2: 'अस्पताल बेड्स खोजें',
    heroTitlePart3: 'रीयल-टाइम में',
    heroSubtitleMain: 'स्वास्थ सेतु (SwasthyaSetu) मरीजों को भारत भर के सत्यापित अस्पताल बेड्स, ICU यूनिट्स और लाइव ब्लड बैंक से जोड़ता है। जब हर सेकंड कीमती हो, तुरंत सत्यापित सहायता पाएँ।',
    findEmergencyBed: 'आपातकालीन बेड खोजें',
    findBed: 'बेड खोजें',
    findBlood: 'रक्त खोजें',
    requestAmbulance: 'एम्बुलेंस बुलाएँ',
    ambulance: 'एम्बुलेंस',
    liveUpdatesIndia: 'भारत भर से लाइव अपडेट्स',
    bedsTracked: 'ट्रैक किए गए बेड्स',
    heroSubtitle: 'भारत भर में सत्यापित अस्पतालों, ब्लड बैंकों और लाइव एम्बुलेंस सेवाओं को जोड़ने वाला रीयल-टाइम आपातकालीन स्वास्थ्य नेटवर्क।',
    findNearbyHospitals: 'निकटतम अस्पताल खोजें',
    emergencySOSCall: 'इमरजेंसी कॉल करें (112)',
    liveHospitalNetwork: 'लाइव अस्पताल नेटवर्क',
    verifiedBeds: 'सत्यापित बेड उपलब्ध',
    bloodUnitsStock: 'रक्त यूनिट उपलब्ध',
    citiesCovered: 'भारत भर के प्रमुख शहर',
    quickEmergencyTitle: 'क्या आपको आपातकालीन चिकित्सा सहायता चाहिए?',
    quickEmergencyDesc: 'अस्पताल पहुँचने तक 10 मिनट के लिए गारंटीकृत ICU / वेंटिलेटर बेड तुरंत रिज़र्व करें।',
    reserveBedNow: 'अभी ICU बेड रिज़र्व करें',
    noBedsAvailable: 'कोई बेड उपलब्ध नहीं',

    // Badges
    verifiedHospitals: 'सत्यापित अस्पताल',
    realTimeUpdatesBadge: 'रीयल-टाइम अपडेट्स',
    support24x7Badge: '24x7 सहायता',

    // Floating Stats
    hospitalsBeds: 'अस्पताल और उपलब्ध बेड्स',
    bloodBanksAvailable: 'ब्लड बैंक उपलब्ध',
    activeAmbulances: 'सक्रिय एम्बुलेंस',
    emergencySupport: 'आपातकालीन सहायता',

    // Problem Statement
    problemWeSolveTitle: 'जिस समस्या का हम समाधान करते हैं',
    problemWeSolveDesc: 'भारत में मेडिकल इमरजेंसी के दौरान, परिवार अस्पताल बेड्स की उपलब्धता जानने में कीमती समय बर्बाद करते हैं। उचित जानकारी के अभाव में कई लोग अपनों को खो देते हैं।',
    problemWeSolveShortDesc: 'भारत में मेडिकल इमरजेंसी के दौरान, परिवार अस्पताल में फोन कर कीमती समय गँवाते हैं।',
    goldenHourLost: 'गोल्डन आवर का नुकसान',
    goldenHourDesc: 'गंभीर चोट/ट्रॉमा के मरीजों के पास जान बचाने के लिए केवल 60 मिनट होते हैं। अधिकांश समय अस्पताल खोजने में ही निकल जाता है।',
    noCentralSystem: 'केंद्रीय नेटवर्क का अभाव',
    noCentralDesc: 'इमरजेंसी में परिवार 10-15 अस्पतालों में कॉल करते हैं। रीयल-टाइम बेड डेटा जनता तक आसानी से नहीं पहुँच पाता।',
    bloodShortage: 'रक्त की कमी',
    bloodShortageDesc: 'भारत में हर साल 15 लाख यूनिट रक्त की कमी होती है। आपातकाल में रक्तदाता ढूंढना बेहद कठिन होता है।',

    // How SwasthyaSetu Helps
    howItHelps: 'स्वास्थ्य सेतु कैसे मदद करता है',
    howItHelpsDesc: 'एक एकीकृत रीयल-टाइम प्लेटफ़ॉर्म जो मरीजों, अस्पतालों और रक्तदाताओं को आपस में जोड़ता है।',
    smartMatching: 'स्मार्ट मैचिंग',
    smartMatchingDesc: 'GPS और लाइव बेड उपलब्धता के आधार पर निकटतम सत्यापित अस्पताल तुरंत खोजें।',
    smartMatchingEngine: 'स्मार्ट मैचिंग इंजन',
    realTimeUpdatesCard: 'रीयल-टाइम अपडेट्स',
    realTimeUpdatesCardDesc: 'सत्यापित अस्पतालों से लाइव बेड और ब्लड डेटा का 24/7 सीधा प्रसारण।',
    adminVerified: 'प्रशासन द्वारा सत्यापित',
    adminVerifiedDesc: 'सुपर एडमिन निरीक्षण द्वारा अस्पताल अवसंरचना और बेड क्षमता 100% सत्यापित।',
    superAdminVerified: 'सुपर एडमिन सत्यापित',
    certifiedWardInventory: 'प्रमाणित वार्ड इन्वेंटरी',
    routeOptimization: 'सटीक रास्ता एवं नेविगेशन',
    routeOptimizationDesc: 'मैप्स एकीकरण के साथ चुने गए अस्पताल तक पहुँचने का सबसे तेज़ रास्ता पाएँ।',
    donorNetwork: 'रक्तदाता नेटवर्क',
    donorNetworkDesc: 'आपातकाल के समय अपने आसपास पंजीकृत रक्तदाताओं से तुरंत संपर्क करें।',
    supportRoundClock: '24x7 सहायता',
    supportRoundClockDesc: '24 घंटे आपकी सहायता के लिए आपातकालीन सपोर्ट टीम हमेशा तैयार।',
    panIndiaCoverage: 'संपूर्ण भारत नेटवर्क',
    panIndiaCoverageDesc: 'भारत के सभी प्रमुख शहरों में उपलब्ध, जहाँ प्रतिदिन नए अस्पताल जुड़ रहे हैं।',

    // How It Works
    howItWorks: 'यह कैसे काम करता है',
    howItWorksDesc: 'तीन आसान चरणों में सही अस्पताल और सहायता से जुड़ें।',
    shareLocationStep: '1. लोकेशन शेयर करें',
    shareLocationStepDesc: 'लोकेशन एक्सेस की अनुमति दें या अपना पता मैन्युअली दर्ज करें।',
    selectEmergencyStep: '2. इमरजेंसी का प्रकार चुनें',
    selectEmergencyStepDesc: 'इमरजेंसी का प्रकार और आवश्यक बेड (ICU, सामान्य, वेंटिलेटर) चुनें।',
    getRecommendationsStep: '3. तुरंत सिफारिशें पाएँ',
    getRecommendationsStepDesc: 'दूरी और उपलब्धता के आधार पर शीर्ष अस्पतालों और उनके रास्तों की सूची देखें।',
    everySecondCounts: 'आपातकाल में हर एक सेकंड कीमती है',
    everySecondCountsDesc: 'अस्पतालों में फोन करके समय बर्बाद न करें। स्वास्थ सेतु से तुरंत उपलब्ध बेड्स खोजें।',
    searchNow: 'अभी खोजें',
    registerAsDonor: 'रक्तदाता के रूप में पंजीकरण करें',

    // Hospitals Page & Cards
    liveBedTracker: 'लाइव बेड ट्रैकर',
    hospitalsDirectoryTitle: 'अस्पताल डायरेक्टरी एवं बेड उपलब्धता',
    hospitalsDirectoryDesc: 'अस्पताल क्षमता, ICU उपलब्धता, वेंटिलेटर स्थिति और लोकेशन का रीयल-टाइम विवरण।',
    searchHospitalsPlaceholder: 'शहर, राज्य या अस्पताल के नाम से खोजें...',
    allCities: 'सभी शहर',
    allBedTypes: 'सभी प्रकार के बेड',
    icuOnly: 'केवल ICU बेड',
    ventilatorOnly: 'केवल वेंटिलेटर बेड',
    generalOnly: 'केवल सामान्य बेड',
    available: 'उपलब्ध',
    totalCapacity: 'कुल क्षमता',
    icuBeds: 'ICU बेड्स',
    generalBeds: 'सामान्य बेड्स',
    ventilatorBeds: 'वेंटिलेटर्स',
    holdBed: '10 मिनट बेड रिज़र्व करें',
    holdingBed: 'रिज़र्व हो रहा है...',
    directions: 'रास्ता देखें',
    verified: 'सत्यापित अस्पताल',
    unverified: 'सत्यापन लंबित',
    blockchainVerified: 'सत्यापित सुविधा',
    contactHospital: 'अस्पताल से संपर्क करें',
    facilitiesSpecialties: 'विशेषज्ञता एवं सुविधाएं',
    noHospitalsFound: 'आपके खोजे गए फ़िल्टर या शहर के लिए कोई अस्पताल नहीं मिला।',
    showingHospitals: 'दिखाए जा रहे हैं',
    hospitalsText: 'अस्पताल',
    verifiedFacilitiesLive: 'सत्यापित सुविधाएं लाइव',
    mapView: 'मैप व्यू',
    hideMap: 'मैप छुपाएँ',
    grid: 'ग्रिड',
    list: 'सूची',
    zoomPinOnMap: 'मैप पर पिन देखें 📍',
    phoneNotListed: 'फोन नंबर उपलब्ध नहीं',
    emergency24x7: '24/7 आपातकालीन सेवा',
    bedHoldModalTitle: 'सत्यापित बेड रिज़र्वेशन (10-मिनट सीमा)',
    bedTicketTitle: 'बेड रिज़र्वेशन टिकट',
    concurrencyLockNotice: 'रीयल-टाइम लॉक और फोन OTP सत्यापन सक्रिय।',
    patientName: 'मरीज का नाम',
    enterPatientName: 'मरीज का पूरा नाम दर्ज करें',
    contactPhone: 'संपर्क फोन नंबर',
    selectBedCategoryHold: 'रिज़र्व करने के लिए बेड श्रेणी चुनें',
    bedsLeft: 'शेष',
    selected: 'चयनित',
    fullZeroLeft: 'फुल / 0 उपलब्ध',
    noBedsAvailableToHold: 'रिज़र्व करने के लिए कोई बेड उपलब्ध नहीं',
    selectedBedCategoryFull: 'चयनित बेड श्रेणी फुल है',
    proceedPhoneVerification: 'फोन सत्यापन के साथ आगे बढ़ें',
    generatingLock: 'वन-टाइम लॉक जारी हो रहा है...',
    otpSentTo: 'OTP भेजा गया',
    enterOtp: '6-अंकों का OTP दर्ज करें',
    back: 'वापस',
    verifyOtpHold: 'OTP सत्यापित करें और बेड रिज़र्व करें',
    verifyingHolding: 'सत्यापन एवं रिज़र्व हो रहा है...',
    bedHoldActive: 'बेड रिज़र्वेशन सक्रिय!',
    showQrAtDesk: 'अस्पताल डेस्क पर यह QR दिखाएँ',
    timeRemaining: 'शेष समय:',
    patientLabel: 'मरीज:',
    bedLabel: 'बेड:',
    hospitalLabel: 'अस्पताल:',
    printTicket: 'प्रिंट / टिकट PDF सेव करें (QR कोड सहित)',
    releaseHold: 'रिज़र्वेशन रद्द करें',
    releasing: 'रद्द हो रहा है...',
    done: 'पूर्ण',

    // Blood Page & Cards
    bloodDirectoryTitle: 'राष्ट्रीय ब्लड बैंक एवं रक्त उपलब्धता',
    bloodDirectoryDesc: 'लाइव ब्लड बैंक स्टॉक, दुर्लभ रक्त समूह और सत्यापित रक्तदाताओं की खोज करें।',
    bloodFinder: 'रक्त उपलब्धता खोजें',
    bloodFinderDesc: 'रक्त उपलब्धता खोजें एवं रक्तदाता के रूप में पंजीकरण करें',
    findBloodTab: 'रक्त खोजें',
    donateBloodTab: 'रक्तदान करें',
    searchBloodAvailability: 'रक्त उपलब्धता खोजें',
    findBloodBanksNear: 'अपने निकट उपलब्ध रक्त यूनिट वाले ब्लड बैंक खोजें',
    bloodGroup: 'रक्त समूह',
    selectBloodGroup: 'रक्त समूह चुनें',
    allBloodGroups: 'सभी रक्त समूह',
    city: 'शहर',
    selectCity: 'शहर चुनें',
    search: 'खोजें',
    searching: 'खोज रहे हैं...',
    showAll: 'सभी दिखाएँ',
    searchBloodStocks: 'रक्त स्टॉक खोजें',
    allGroups: 'सभी रक्त समूह (A+, B+, O+, AB-...)',
    unitsInStock: 'उपलब्ध यूनिट्स',
    units: 'यूनिट्स',
    call: 'कॉल करें',
    lastUpdated: 'अंतिम अपडेट',
    contactBloodBank: 'ब्लड बैंक से संपर्क करें',
    requestBloodUnits: 'रक्त आवश्यकता की मांग करें',
    registerAsBloodDonor: 'रक्तदाता के रूप में पंजीकरण करें',
    joinDonorNetworkDesc: 'रक्तदाता नेटवर्क में शामिल होने के लिए अपना विवरण भरें',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    email: 'ईमेल',
    ageYears: 'आयु (वर्ष)',
    weightKg: 'वजन (किग्रा)',
    registerDonorBtn: 'रक्तदाता पंजीकरण करें',
    criticalShortageAlert: 'चेतावनी: कई शहरों में O- और AB- रक्त समूह की भारी कमी है।',
    noBloodFound: 'चयनित शहर या रक्त समूह के लिए कोई स्टॉक नहीं मिला।',
    foundBloodBanks: 'कुल',
    bloodBanksCount: 'ब्लड बैंक मिले',
    whyDonateBlood: 'रक्तदान क्यों करें?',
    saveLives: 'जीवन बचाएँ',
    saveLivesDesc: 'एक रक्तदान 3 लोगों की जान बचा सकता है',
    quickProcess: 'तेज़ प्रक्रिया',
    quickProcessDesc: 'पूरी प्रक्रिया में केवल 30-45 मिनट लगते हैं',
    healthBenefits: 'स्वास्थ्य लाभ',
    healthBenefitsDesc: 'मुफ्त स्वास्थ्य जांच और हृदय संबंधी रोगों के जोखिम में कमी',
    eligibilityCriteria: 'पात्रता मानदंड',
    eligibilityAge: 'आयु 18-65 वर्ष के बीच',
    eligibilityWeight: 'वजन न्यूनतम 50 किग्रा',
    eligibilityHemoglobin: 'हीमोग्लोबिन स्तर 12.5 g/dL से अधिक',
    eligibilityIllness: 'पिछले 6 महीनों में कोई गंभीर बीमारी नहीं',
    eligibilityGap: 'पिछले रक्तदान से 56 दिनों का अंतर',

    // Emergency Page & Components
    emergencySOSTitle: 'आपातकालीन चिकित्सा सहायता एवं तत्काल बेड होल्ड',
    emergencySOSDesc: 'रीयल-टाइम जीपीएस लोकेशन के आधार पर 10 मिनट के लिए गारंटीकृत बेड रिज़र्वेशन।',
    liveSOSDispatch: 'लाइव SOS डिस्पैच',
    emergencySearchTitle: 'आपातकालीन खोज',
    emergencySearchDesc: 'उपलब्ध बेड्स और लाइव एम्बुलेंस सहायता के साथ निकटतम अस्पताल खोजें',
    enterDetails: 'विवरण दर्ज करें',
    selectHospital: 'अस्पताल चुनें',
    yourLocation: 'आपकी लोकेशन',
    locationDesc: 'नजदीकी अस्पताल और बेड्स खोजने के लिए हमें आपकी लोकेशन की आवश्यकता है',
    useCurrentLocation: 'वर्तमान लोकेशन का उपयोग करें',
    detectingLocation: 'लोकेशन खोजी जा रही है...',
    orEnterManually: 'या मैन्युअली पता दर्ज करें',
    addressLandmark: 'पता या नजदीकी स्थान',
    addressPlaceholder: 'अपना पता, क्षेत्र या शहर दर्ज करें...',
    gpsDetectedSuccess: 'जीपीएस लोकेशन सफलतापूर्वक मिल गई',
    emergencyDetails: 'आपातकालीन विवरण',
    emergencyDetailsDesc: 'आपकी आवश्यकता अनुसार सही अस्पताल एवं उपकरण खोजने में सहायता करें',
    emergencyType: 'इमरजेंसी का प्रकार',
    selectEmergencyType: 'इमरजेंसी का प्रकार चुनें',
    traumaAccident: 'ट्रॉमा / दुर्घटना',
    cardiacEmergency: 'हृदय रोग संबंधी इमरजेंसी',
    strokeEmergency: 'स्ट्रोक / लकवा',
    respiratoryEmergency: 'सांस लेने में तकलीफ',
    otherEmergency: 'अन्य इमरजेंसी',
    requiredBedType: 'आवश्यक बेड का प्रकार',
    icuBed: 'ICU बेड',
    icuBedDesc: 'गहन चिकित्सा इकाई',
    generalBed: 'सामान्य बेड',
    generalBedDesc: 'मानक अस्पताल बेड',
    ventilator: 'वेंटिलेटर',
    ventilatorDesc: 'वेंटिलेटर सहायता के साथ',
    contactPhoneLabel: 'संपर्क फोन नंबर *',
    patientNameLabel: 'मरीज का नाम (वैकल्पिक)',
    findHospitalsButton: 'आपातकालीन अस्पताल खोजें',
    findingHospitals: 'नजदीकी अस्पताल खोज रहे हैं...',
    recommendedHospitals: 'अनुशंसित अस्पताल',
    modifySearch: 'सर्च बदलें',
    backToSearchForm: 'वापस सर्च फॉर्म पर जाएँ',
    callHospital: 'अस्पताल को कॉल करें',
    aiMatch: 'एआई मैच',
    emergencyAmbulanceDispatch: 'आपातकालीन एम्बुलेंस डिस्पैच',
    ambulanceDispatchDesc: 'आपकी लोकेशन के पास रीयल-टाइम जीपीएस ट्रैक की गई एम्बुलेंस',
    gpsLive: 'जीपीएस लाइव',
    callDriver: 'ड्राइवर को कॉल करें',
    dispatchNow: 'अभी भेजें',
    enRoute: 'रास्ते में है',
    noAmbulancesActive: 'अभी कोई सक्रिय एम्बुलेंस उपलब्ध नहीं है',
    noAmbulancesDesc: 'इस क्षेत्र में कोई सत्यापित एम्बुलेंस सक्रिय नहीं है। सीधी सरकारी सहायता के लिए हेल्पलाइन 112 डायल करें।',
    nationalHelplines: 'राष्ट्रीय आपातकालीन हेल्पलाइन',
    ambulance102: 'एम्बुलेंस हेल्पलाइन: 102 / 108',
    disaster112: 'राष्ट्रीय आपातकालीन सेवा: 112',
    helplinesTitle: 'आपातकालीन हेल्पलाइन्स',
    govtSos: '24/7 सरकारी हेल्पलाइन',
    emergency: {
      helplines: 'आपातकालीन हेल्पलाइन्स',
      ambulance: 'एम्बुलेंस हेल्पलाइन',
      national: 'राष्ट्रीय आपातकालीन'
    },

    // Hospital Onboarding Modal
    hospitalRegisterTitle: 'अस्पताल ऑनबोर्डिंग एवं पंजीकरण',
    hospitalRegisterDesc: 'अपने अस्पताल को स्वास्थ सेतु राष्ट्रीय आपातकालीन नेटवर्क से जोड़ें',
    hospitalFullName: 'अस्पताल का पूरा नाम *',
    hospitalType: 'अस्पताल का प्रकार',
    privateHospital: 'निजी अस्पताल (Private)',
    govtHospital: 'सरकारी अस्पताल (Government)',
    charitableHospital: 'चैरिटेबल / ट्रस्ट',
    licenseNumber: 'HFR / पंजीकरण लाइसेंस संख्या',
    phoneContact: 'इमरजेंसी संपर्क फोन नंबर',
    cityName: 'शहर *',
    stateName: 'राज्य / केंद्र शासित प्रदेश',
    fullAddress: 'पूरा पता',
    adminLoginEmail: 'एडमिन लॉगिन ईमेल *',
    adminPassword: 'एडमिन पासवर्ड *',
    submitApplication: 'पंजीकरण आवेदन जमा करें',
    submittingApp: 'आवेदन जमा हो रहा है...',
    applicationSubmitted: 'आवेदन सफलतापूर्वक जमा हो गया!',

    // Admin & Login
    hospitalAdminPortal: 'अस्पताल एडमिन पोर्टल',
    superAdminControl: 'सुपर एडमिन कंट्रोल रूम',
    hospitalStaffLogin: 'अस्पताल स्टाफ एवं नोडल अधिकारी लॉगिन',
    superAdminLoginTitle: 'मंत्रालय सुपर एडमिन कंट्रोल रूम',
    updateBedsButton: 'बेड अपडेट करें',
    updateBedsTitle: 'बेड उपलब्धता अपडेट करें',
    saveBedUpdates: 'बेड अपडेट सेव करें',
    cancel: 'रद्द करें',

    // Footer
    footerDesc: 'स्वास्थ सेतु भारत का एकीकृत रीयल-टाइम आपातकालीन स्वास्थ्य नेटवर्क है जो बेड उपलब्धता, रक्त स्टॉक और एम्बुलेंस सेवाओं को संचालित करता है।',
    quickLinks: 'महत्वपूर्ण लिंक्स',
    facilityOnboarding: 'चिकित्सा सुविधा ऑनबोर्डिंग',
    registerBloodBankLink: 'ब्लड बैंक पंजीकृत करें',
    registerAmbulanceLink: 'एम्बुलेंस पंजीकृत करें',
    contactUs: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम एवं शर्तें',
    rightsReserved: 'सर्वाधिकार सुरक्षित। स्वास्थ सेतु राष्ट्रीय स्वास्थ्य नेटवर्क।',
    allRightsReservedShort: '© 2026 स्वास्थ सेतु। सर्वाधिकार सुरक्षित।',
    police100: 'पुलिस: 100',
    fire101: 'अग्निशमन: 101'
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => { },
  t: (key) => key
});

function resolveKey(dict, path) {
  if (!dict || !path) return undefined;
  if (dict[path] !== undefined) return dict[path];
  if (typeof path === 'string' && path.includes('.')) {
    const parts = path.split('.');
    let cur = dict;
    for (const part of parts) {
      if (cur && typeof cur === 'object' && part in cur) {
        cur = cur[part];
      } else {
        return undefined;
      }
    }
    return typeof cur === 'string' ? cur : undefined;
  }
  return undefined;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('swasthya_lang') || 'en';
  });
  const [aiCache, setAiCache] = useState({});

  useEffect(() => {
    localStorage.setItem('swasthya_lang', language);
  }, [language]);

  const t = (key) => {
    if (!key) return '';
    const staticMatch = resolveKey(translations[language], key) ?? resolveKey(translations['en'], key);
    if (staticMatch !== undefined) return staticMatch;

    // Check AI dynamic cache
    const cacheKey = `${language}:${key}`;
    if (aiCache[cacheKey]) return aiCache[cacheKey];

    return key;
  };

  const tAsync = async (text, overrideLang) => {
    const targetLang = overrideLang || language;
    if (!text || targetLang === 'en') return text;

    const cacheKey = `${targetLang}:${text}`;
    if (aiCache[cacheKey]) return aiCache[cacheKey];

    try {
      const res = await apiCall('/api/translate', {
        method: 'POST',
        body: { text, targetLang }
      });
      if (res?.translatedText) {
        setAiCache(prev => ({ ...prev, [cacheKey]: res.translatedText }));
        return res.translatedText;
      }
    } catch (err) {
      console.warn('AI Translation warning:', err);
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tAsync }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
